### ISSUE TITLE
Proxy username not mentioned in docs

### ISSUE THREAD

**Issue by tgam-sid** [dockerzone/shadowsocks-server#1]
Hi,

I've got the shadowsocks server up and running following your instructions but only the password is mentioned in the README and the docker-compose.yml file. I can't seem what should be the username to input in my web browser's proxy settings. Am I missing something here?

--
Thanks

**Comment by omid** [comment]
Hello,

Shadowsocks doesn't have any username, the password works as a key.
And you cannot set it in your browser, you need a Shadowsocks client. You can find them here: https://shadowsocks.org/en/download/clients.html

Best

**Comment by tgam-sid** [comment]
Thanks, Omid. Sorry for the n00b question. I figured this out eventually.

**Comment by omid** [comment]
No problem. You're always welcome.
